# File: .github/workflows/repo-sync.yml
name: KOP-XIAO-QuantumultX-Surge-API
on:
  schedule:
    - cron: '5 12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: KOP-XIAO-QuantumultX-Surge-API
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: KOP-XIAO-QuantumultX-Surge-API
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/KOP-XIAO/QuantumultX-Surge-API.git"
          source_branch: "master"
          destination_branch: "KOP-XIAO-QuantumultX-Surge-API"
          github_token: ${{ secrets.PAT }}